<?php

namespace App\Jobs;

use App\Models\VpnUser;
use Illuminate\Bus\Queueable;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;

class GenerateVpnConfig implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected VpnUser $vpnUser;
    protected string $protocol;

    /**
     * @param VpnUser $vpnUser
     * @param string $protocol ('openvpn' or 'wireguard')
     */
    public function __construct(VpnUser $vpnUser, string $protocol)
    {
        $this->vpnUser = $vpnUser->load('vpnServers');
        $this->protocol = strtolower($protocol);
    }

    public function handle(): void
    {
        Log::info("🚀 Generating VPN configuration for {$this->vpnUser->username} using $this->protocol protocol.");

        foreach ($this->vpnUser->vpnServers as $server) {
            if ($this->protocol === 'openvpn') {
                $this->generateOvpnConfig($server);
            } elseif ($this->protocol === 'wireguard') {
                $this->generateWireguardConfig($server);
            } else {
                Log::warning("❌ Unknown VPN protocol: $this->protocol");
            }
        }

        Log::info("🎉 Finished generating configurations for {$this->vpnUser->username}.");
    }

    protected function generateOvpnConfig($server): void
    {
        Log::info("🔧 Generating OVPN config for server: $server->name ($server->ip_address)");

        // Fetch server certificate files
        $files = [
            'ca' => '/etc/openvpn/ca.crt',
            'ta' => '/etc/openvpn/ta.key',
        ];

        $fetched = [];
        foreach ($files as $label => $path) {
            $content = $this->fetchRemoteFile($server->ip_address, $path, strtoupper($label));
            if (!$content) {
                Log::error("❌ [OVPN] Missing $label for server $server->name, skipping.");
                return;
            }
            $fetched[$label] = $content;
        }

        // Build OVPN config
        $username = $this->vpnUser->username;
        $ip = $server->ip_address;

        $config = <<<EOL
# Auto-generated by AIOVPN
client
dev tun
proto udp
remote $ip 1194
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA256
cipher AES-256-GCM
ncp-ciphers AES-256-GCM: AES-128-GCM
auth-user-pass
verb 3

<ca>
{$fetched['ca']}
</ca>

<tls-auth>
{$fetched['ta']}
</tls-auth>
key-direction 1
EOL;

        // Save config
        $fileName = "public/ovpn_configs/{$server->name}_$username.ovpn";
        Storage::put($fileName, $config);
        Storage::setVisibility($fileName, 'public');

        Log::info("✅ [OVPN] Config saved: storage/app/$fileName");
    }

    protected function generateWireguardConfig($server): void
    {
        Log::info("🔧 Generating WireGuard config for server: $server->name ($server->ip_address)");

        // Fetch public IP and keys
        $userKeys = $this->vpnUser->only(['wireguard_private_key', 'wireguard_public_key', 'wireguard_address']);
        if (empty($userKeys['wireguard_public_key']) || empty($userKeys['wireguard_address'])) {
            Log::error("❌ [WG] Missing WireGuard keys for {$this->vpnUser->username}, skipping.");
            return;
        }

        $serverPublicKey = $this->fetchRemoteFile($server->ip_address, '/etc/wireguard/server_public_key', 'SERVER_PUBLIC_KEY');
        if (!$serverPublicKey) {
            Log::error("❌ [WG] Failed to fetch server public key for $server->name, skipping.");
            return;
        }

        // Generate WireGuard config
        $clientConfig = <<<EOL
[Interface]
PrivateKey = {$userKeys['wireguard_private_key']}
Address = {$userKeys['wireguard_address']}
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = {$serverPublicKey}
Endpoint = $server->ip_address:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 15
EOL;

        // Save config
        $fileName = "public/wg_configs/{$server->name}_{$this->vpnUser->username}.conf";
        Storage::put($fileName, $clientConfig);
        Storage::setVisibility($fileName, 'public');

        Log::info("✅ [WG] Config saved: storage/app/$fileName");
    }

    private function fetchRemoteFile(string $ip, string $remotePath, string $label): ?string
    {
        $sshKey = storage_path('app/ssh_keys/id_rsa');
        $sshUser = 'root';
        $command = "ssh -i $sshKey -o StrictHostKeyChecking=no $sshUser@$ip 'cat $remotePath'";

        exec($command, $output, $status);
        if ($status !== 0 || empty($output)) {
            Log::error("❌ Failed to fetch $label from $ip.");
            return null;
        }

        return implode("\n", $output);
    }
}
